spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#        auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

  server:
    port: 8443
    ssl:
      key-store: classpath:keystore.p12
      key-store-password: qwer1234
      key-store-type: PKCS12
      key-alias: myapp

  datasource:
    url: jdbc:mysql://localhost:3306/fitple_project
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key:
server:
  port: 8080

cors:
  allowed-origins: http://localhost:3003
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true